void update()
{
    ...
    foo = (float *)malloc(a * 2 * sizeof(float));
    ...
    bar = (float *)realloc(foo, a * 2 * sizeof(float));
    ...
    free(foo);
    foo = NULL; // Set foo to NULL after freeing to avoid double-free issues
    ...
}
