char *tdata[3] = {"   ", "2014", "Fixe!"};
char *tdata[3];
tdata[0] = strdup("   ");
tdata[1] = strdup("2014");
tdata[2] = strdup("Fixe!");
char * s = "ABC";
printf("%s\n",s);
sprintf(s,"DEF");
char s[4] = "ABC";
printf("%s\n", s);
strcpy(s, "DEF");
printf("%s\n", s);
